# Generated by Django 3.2.3 on 2021-05-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=5)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
