# Generated by Django 3.2.3 on 2021-05-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanagement', '0002_remove_employee_emp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpId', models.CharField(max_length=3)),
                ('salary', models.CharField(max_length=100)),
            ],
        ),
    ]
