# Generated by Django 3.2.3 on 2021-05-30 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanagement', '0003_employeesalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeemanagement.employeesalary'),
        ),
    ]
