# Generated by Django 3.2.3 on 2021-05-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_auto_20210531_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Programmer', 'Programmer'), ('SEO', 'SEO'), ('HR', 'HR')], max_length=10),
        ),
    ]
