# Generated by Django 3.2.3 on 2021-05-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalary',
            name='title',
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='salary',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('J', 'Java'), ('P', 'Python'), ('L', 'Large')], max_length=1),
        ),
    ]
