# Generated by Django 3.2.3 on 2021-05-31 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_auto_20210531_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesalary',
            old_name='salary',
            new_name='Textarea',
        ),
    ]
