# Generated by Django 3.2.3 on 2021-05-31 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_rename_salary_employeesalary_textarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesalary',
            old_name='Textarea',
            new_name='Salary',
        ),
    ]
