# Generated by Django 3.2.3 on 2021-05-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_rename_textarea_employeesalary_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='Salary',
            field=models.IntegerField(choices=[('20k', '20000'), ('30k', '30000'), ('40k', '40000')]),
        ),
    ]
