# Generated by Django 3.2.3 on 2021-05-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_rename_salary_employeesalary_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
