# Generated by Django 3.2.3 on 2021-05-31 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_alter_employeesalary_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesalary',
            old_name='salary',
            new_name='title',
        ),
    ]
