# Generated by Django 3.2.3 on 2021-05-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_rename_salary_employeesalary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
