# Generated by Django 3.2.3 on 2021-05-31 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_alter_employeesalary_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesalary',
            old_name='title',
            new_name='salary',
        ),
    ]
