# Generated by Django 3.2.3 on 2021-05-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_rename_title_employeesalary_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
