# Generated by Django 3.2.3 on 2021-05-31 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0012_auto_20210531_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_code',
        ),
    ]
